version: '3.8'

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: addis-api
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGODB_URI: ${MONGODB_URI}
    depends_on:
      - mongo
    networks:
      - addis-network

  mongo:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo-data:/data/db
    networks:
      - addis-network

networks:
  addis-network:
    driver: bridge

volumes:
  mongo-data:
